### ISSUE TITLE
BASE: Dialog

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Taarafo.Web#16]

**Comment by stasnowak** [comment]
@hassanhabib Hi, what kind of dialog is being mentioned here? I could add the html dialog tag like https://www.w3schools.com/tags/tag_dialog.asp and parameterize it. Although it states that it is not supported in Safari. Alternatively i could add already the syncfusion library as dependency that contains a dialog component  https://www.syncfusion.com/blazor-components/blazor-modal-dialog and parameterize this then. Let me know, how i should proceed ;)

**Comment by hassanhabib** [comment]
@stasnowak this one might require a pairing session. The place where you are looking in Syncfusion is exactly where we are going. We just need to wrap up their external component with a base component. Then just allow adding things like header, buttons and text in it.

So we need a DialogBase. That has ChildContent and maybe Footer for the button.
We need ButtonBase and TextAreaBase.
Look into building Multi-Line TextAreaBase with Syncfusion if you can. I think it's super simply but we don't have it today.

Ultimately the dialog will look something like this:

![image](https://user-images.githubusercontent.com/1453985/141673676-2b693ef5-2369-4419-9386-9257d2390881.png)

**Comment by stasnowak** [comment]
@hassanhabib Ok will take care with Multi-Line TextAreaBase with Syncfusion then we can get back to this one ;) Thanks for clarification

**Comment by stasnowak** [comment]
@hassanhabib With PR #34 We have the text area and with PR #35 the ButtonBase is also syncfusion one. So we should have everything needed for this one. 

Let me know if we should pair for this one, or if i should try to implement it, and you can then review it ;)

**Comment by hassanhabib** [comment]
@stasnowak that's right. You won't even be using those - you just need to offer the container of a dialog - here's some capabilities that we need to have for it's API:
`Show()`
`Hide()`
`OnExitEvent(...)`


Then properties like:
`<DialogHeader />`
`<DialogContent />`
`<DialogFooter />`

We might need to pair on this one.
