### ISSUE TITLE
COMPONENT: Render Posts

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Taarafo.Web#28]

**Comment by stasnowak** [comment]
@hassanhabib Hay Hassan. I want to work on this, but i'm not sure how we want to render those Posts. Should I go for a GridBase like we do in TeachersComponent in OtripleS.Portal.Web, or do you think a different syncfusion control is more suitable. My idea was like a syncfusion ListView which would be ListViewBase for us.

**Comment by stasnowak** [comment]
If you however like the GridBase for now, i created the #43  Pull Request

**Comment by hassanhabib** [comment]
@stasnowak let's setup a pairing session so we can render posts. It's not going to be a Grid. It's going to be a component with a label and dates - let's setup sometime to pair on this.
